
.PHONY: run test

run: main.go node/*
	go run main.go

run_handout: main.go node/*
	go run main.go ./files/handout.txt

run_input: main.go node/*
	go run main.go ./files/input.txt

test: main.go
	go test

